### PR TITLE
fix: memory leak

### PR DESCRIPTION
**Pull request by luca020400**

### CODE REVIEW

**Comment by luca020400** [comment]
TL; DR: Fixes memory leak that make it use ~6GB of RAM while extracting a payload, now it uses ~1.7GB

**Comment by luca020400** [comment]
Ideally we'd be using a golang xz impl (https://github.com/ulikunitz/xz) , but it's rather slow compared to this C one.
Still requiring lzma to be installed kinda sucks.

**Comment by ssut** [comment]
Thanks for your contribution.
Anyway, the reason I didn't use https://github.com/ulikunitz/xz is written in https://github.com/ssut/payload-dumper-go/issues/3#issuecomment-811729853.

**Comment by luca020400** [comment]
Yeah, I switched to it as a test and all the output files are somehow broken.
Not sure how is possible given the sha/block size checks never fail.

Either way, the impl is also shower

**Pull request merged**
